version: "2"
services:
  db:
    image: mysql:5.7
    container_name: servicemysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  web:
    container_name: servicephp
    volumes:
      - .\src\html:/var/www/html
    depends_on:
      - db
    image: cicerorod/php-7.0apache:v1
    links:
      - db
    ports:
      - "8001:80"
    restart: always
